// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PackageDelivery.Infrastructure.Context;

#nullable disable

namespace PackageDelivery.Infrastructure.Migrations
{
    [DbContext(typeof(PackageDeliveryDbContext))]
    partial class PackageDeliveryDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("PackageDelivery.Infrastructure.Entities.ApiRestLog", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<DateTime?>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("CreatedDateUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("Host")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("Origin")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Path")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("QueryString")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<string>("RequestBody")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ResponseBody")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Scheme")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<byte[]>("Version")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.HasKey("Id");

                    b.HasIndex(new[] { "CreatedDateUtc" }, "IX_ApiRestLogs_CreatedDateUtc")
                        .IsDescending();

                    b.ToTable("ApiRestLogs", (string)null);
                });

            modelBuilder.Entity("PackageDelivery.Infrastructure.Entities.AspNetRole", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("PackageDelivery.Infrastructure.Entities.AspNetRoleClaim", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<long>("RoleId")
                        .HasColumnType("bigint");

                    b.Property<long?>("RoleId1")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.HasIndex(new[] { "RoleId1" }, "IX_AspNetRoleClaims_RoleId1");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("PackageDelivery.Infrastructure.Entities.AspNetUser", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<bool>("Active")
                        .HasColumnType("bit");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CreatedBy")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("CreatedDateUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("FullName")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("Name")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UpdatedBy")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("UpdatedDateUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<byte[]>("Version")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("PackageDelivery.Infrastructure.Entities.AspNetUserClaim", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<long>("UserId")
                        .HasColumnType("bigint");

                    b.Property<long?>("UserId1")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.HasIndex(new[] { "UserId1" }, "IX_AspNetUserClaims_UserId1");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("PackageDelivery.Infrastructure.Entities.AspNetUserLogin", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<long>("UserId")
                        .HasColumnType("bigint");

                    b.Property<long?>("UserId1")
                        .HasColumnType("bigint");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.HasIndex(new[] { "UserId1" }, "IX_AspNetUserLogins_UserId1");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("PackageDelivery.Infrastructure.Entities.AspNetUserRole", b =>
                {
                    b.Property<long>("UserId")
                        .HasColumnType("bigint");

                    b.Property<long>("RoleId")
                        .HasColumnType("bigint");

                    b.Property<long?>("RoleId1")
                        .HasColumnType("bigint");

                    b.Property<long?>("UserId1")
                        .HasColumnType("bigint");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.HasIndex(new[] { "RoleId1" }, "IX_AspNetUserRoles_RoleId1");

                    b.HasIndex(new[] { "UserId1" }, "IX_AspNetUserRoles_UserId1");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("PackageDelivery.Infrastructure.Entities.AspNetUserToken", b =>
                {
                    b.Property<long>("UserId")
                        .HasColumnType("bigint");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<long?>("UserId1")
                        .HasColumnType("bigint");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.HasIndex(new[] { "UserId1" }, "IX_AspNetUserTokens_UserId1");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("PackageDelivery.Infrastructure.Entities.Delivery", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<decimal?>("Amount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("BarCode")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("ClientReference")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("CreatedBy")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("CreatedDateUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("Instructions")
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<int>("NumberOfVolumes")
                        .HasColumnType("int");

                    b.Property<string>("PreferentialPeriod")
                        .HasMaxLength(23)
                        .HasColumnType("nvarchar(23)");

                    b.Property<string>("ReceiverAddress")
                        .IsRequired()
                        .HasMaxLength(400)
                        .HasColumnType("nvarchar(400)");

                    b.Property<string>("ReceiverAddressCountryCode")
                        .HasMaxLength(3)
                        .HasColumnType("nvarchar(3)");

                    b.Property<string>("ReceiverAddressPlace")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("ReceiverAddressZipCode")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("ReceiverAddressZipCodePlace")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("ReceiverContactEmail")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("ReceiverContactName")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("ReceiverContactPhoneNumber")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("ReceiverName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("SenderAddress")
                        .IsRequired()
                        .HasMaxLength(400)
                        .HasColumnType("nvarchar(400)");

                    b.Property<string>("SenderAddressCountryCode")
                        .HasMaxLength(3)
                        .HasColumnType("nvarchar(3)");

                    b.Property<string>("SenderAddressPlace")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("SenderAddressZipCode")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("SenderAddressZipCodePlace")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("SenderContactEmail")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("SenderContactName")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("SenderContactPhoneNumber")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("SenderName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<decimal>("TotalWeightOfVolumes")
                        .HasColumnType("decimal(18,3)");

                    b.Property<string>("UpdatedBy")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("UpdatedDateUtc")
                        .HasColumnType("datetime2");

                    b.Property<long>("UserId")
                        .HasColumnType("bigint");

                    b.Property<byte[]>("Version")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.HasKey("Id");

                    b.HasIndex(new[] { "BarCode" }, "IX_Deliveries_BarCode")
                        .IsUnique();

                    b.HasIndex(new[] { "UserId" }, "IX_Deliveries_UserId");

                    b.ToTable("Deliveries", (string)null);
                });

            modelBuilder.Entity("PackageDelivery.Infrastructure.Entities.DeliveryAttribute", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int");

                    b.Property<string>("DeliveryAttributeENG")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("DeliveryAttributeES")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("DeliveryAttributePT")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.ToTable("DeliveryAttributes", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            DeliveryAttributeENG = "Proof of delivery",
                            DeliveryAttributeES = "Prueba de entrega",
                            DeliveryAttributePT = "Prova de entrega"
                        },
                        new
                        {
                            Id = 2,
                            DeliveryAttributeENG = "Same day",
                            DeliveryAttributeES = "Mismo día",
                            DeliveryAttributePT = "Mesmo dia"
                        },
                        new
                        {
                            Id = 3,
                            DeliveryAttributeENG = "Cash on delivery",
                            DeliveryAttributeES = "Contra reembolso",
                            DeliveryAttributePT = "Pagamento na entrega"
                        });
                });

            modelBuilder.Entity("PackageDelivery.Infrastructure.Entities.DeliveryDeliveryAttribute", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<int>("DeliveryAttributeId")
                        .HasColumnType("int");

                    b.Property<long>("DeliveryId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("DeliveryAttributeId");

                    b.HasIndex(new[] { "DeliveryId", "DeliveryAttributeId" }, "IX_DeliveryDeliveryAttributes_Delivery_Attribute")
                        .IsUnique();

                    b.ToTable("DeliveryDeliveryAttributes", (string)null);
                });

            modelBuilder.Entity("PackageDelivery.Infrastructure.Entities.Event", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("CreatedDateUtc")
                        .HasColumnType("datetime2");

                    b.Property<long>("DeliveryId")
                        .HasColumnType("bigint");

                    b.Property<int>("EventTypeId")
                        .HasColumnType("int");

                    b.Property<long?>("PackageId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex(new[] { "DeliveryId" }, "IX_Events_DeliveryId");

                    b.HasIndex(new[] { "EventTypeId" }, "IX_Events_EventTypeId");

                    b.HasIndex(new[] { "PackageId" }, "IX_Events_PackageId");

                    b.ToTable("Events", (string)null);
                });

            modelBuilder.Entity("PackageDelivery.Infrastructure.Entities.EventType", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int");

                    b.Property<string>("EventTypeENG")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("EventTypeES")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("EventTypePT")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.ToTable("EventTypes", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            EventTypeENG = "Created delivery",
                            EventTypeES = "Envío creado",
                            EventTypePT = "Entrega criada"
                        },
                        new
                        {
                            Id = 2,
                            EventTypeENG = "Picked up by carrier",
                            EventTypeES = "Recogido por el transportista",
                            EventTypePT = "Recolhido pelo transportador"
                        },
                        new
                        {
                            Id = 3,
                            EventTypeENG = "In transit",
                            EventTypeES = "En tránsito",
                            EventTypePT = "Em trânsito"
                        },
                        new
                        {
                            Id = 4,
                            EventTypeENG = "Delivered to receiver",
                            EventTypeES = "Entregado al destinatario",
                            EventTypePT = "Entregue ao destinatário"
                        },
                        new
                        {
                            Id = 5,
                            EventTypeENG = "Unable to make pickup",
                            EventTypeES = "No se pudo recoger",
                            EventTypePT = "Não foi possível recolher"
                        },
                        new
                        {
                            Id = 6,
                            EventTypeENG = "Unable to make delivery",
                            EventTypeES = "No se pudo entregar",
                            EventTypePT = "Não foi possível entregar"
                        },
                        new
                        {
                            Id = 7,
                            EventTypeENG = "Returned to sender",
                            EventTypeES = "Devuelto al remitente",
                            EventTypePT = "Devolvido ao remetente"
                        });
                });

            modelBuilder.Entity("PackageDelivery.Infrastructure.Entities.Package", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("CreatedDateUtc")
                        .HasColumnType("datetime2");

                    b.Property<long>("DeliveryId")
                        .HasColumnType("bigint");

                    b.Property<string>("PackageBarCode")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("PackageNumber")
                        .HasColumnType("int");

                    b.Property<byte[]>("Version")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<decimal>("Weight")
                        .HasColumnType("decimal(18,3)");

                    b.HasKey("Id");

                    b.HasIndex(new[] { "DeliveryId" }, "IX_Packages_DeliveryId");

                    b.HasIndex(new[] { "PackageBarCode" }, "IX_Packages_PackageBarCode");

                    b.ToTable("Packages", (string)null);
                });

            modelBuilder.Entity("PackageDelivery.Infrastructure.Entities.AspNetRoleClaim", b =>
                {
                    b.HasOne("PackageDelivery.Infrastructure.Entities.AspNetRole", "Role")
                        .WithMany("AspNetRoleClaimRoles")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PackageDelivery.Infrastructure.Entities.AspNetRole", "RoleId1Navigation")
                        .WithMany("AspNetRoleClaimRoleId1Navigations")
                        .HasForeignKey("RoleId1");

                    b.Navigation("Role");

                    b.Navigation("RoleId1Navigation");
                });

            modelBuilder.Entity("PackageDelivery.Infrastructure.Entities.AspNetUserClaim", b =>
                {
                    b.HasOne("PackageDelivery.Infrastructure.Entities.AspNetUser", "User")
                        .WithMany("AspNetUserClaimUsers")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PackageDelivery.Infrastructure.Entities.AspNetUser", "UserId1Navigation")
                        .WithMany("AspNetUserClaimUserId1Navigations")
                        .HasForeignKey("UserId1");

                    b.Navigation("User");

                    b.Navigation("UserId1Navigation");
                });

            modelBuilder.Entity("PackageDelivery.Infrastructure.Entities.AspNetUserLogin", b =>
                {
                    b.HasOne("PackageDelivery.Infrastructure.Entities.AspNetUser", "User")
                        .WithMany("AspNetUserLoginUsers")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PackageDelivery.Infrastructure.Entities.AspNetUser", "UserId1Navigation")
                        .WithMany("AspNetUserLoginUserId1Navigations")
                        .HasForeignKey("UserId1");

                    b.Navigation("User");

                    b.Navigation("UserId1Navigation");
                });

            modelBuilder.Entity("PackageDelivery.Infrastructure.Entities.AspNetUserRole", b =>
                {
                    b.HasOne("PackageDelivery.Infrastructure.Entities.AspNetRole", "Role")
                        .WithMany("AspNetUserRoleRoles")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PackageDelivery.Infrastructure.Entities.AspNetRole", "RoleId1Navigation")
                        .WithMany("AspNetUserRoleRoleId1Navigations")
                        .HasForeignKey("RoleId1");

                    b.HasOne("PackageDelivery.Infrastructure.Entities.AspNetUser", "User")
                        .WithMany("AspNetUserRoleUsers")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PackageDelivery.Infrastructure.Entities.AspNetUser", "UserId1Navigation")
                        .WithMany("AspNetUserRoleUserId1Navigations")
                        .HasForeignKey("UserId1");

                    b.Navigation("Role");

                    b.Navigation("RoleId1Navigation");

                    b.Navigation("User");

                    b.Navigation("UserId1Navigation");
                });

            modelBuilder.Entity("PackageDelivery.Infrastructure.Entities.AspNetUserToken", b =>
                {
                    b.HasOne("PackageDelivery.Infrastructure.Entities.AspNetUser", "User")
                        .WithMany("AspNetUserTokenUsers")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PackageDelivery.Infrastructure.Entities.AspNetUser", "UserId1Navigation")
                        .WithMany("AspNetUserTokenUserId1Navigations")
                        .HasForeignKey("UserId1");

                    b.Navigation("User");

                    b.Navigation("UserId1Navigation");
                });

            modelBuilder.Entity("PackageDelivery.Infrastructure.Entities.DeliveryDeliveryAttribute", b =>
                {
                    b.HasOne("PackageDelivery.Infrastructure.Entities.DeliveryAttribute", "DeliveryAttribute")
                        .WithMany("DeliveryDeliveryAttributes")
                        .HasForeignKey("DeliveryAttributeId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("PackageDelivery.Infrastructure.Entities.Delivery", "Delivery")
                        .WithMany("DeliveryDeliveryAttributes")
                        .HasForeignKey("DeliveryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Delivery");

                    b.Navigation("DeliveryAttribute");
                });

            modelBuilder.Entity("PackageDelivery.Infrastructure.Entities.Event", b =>
                {
                    b.HasOne("PackageDelivery.Infrastructure.Entities.Delivery", "Delivery")
                        .WithMany("Events")
                        .HasForeignKey("DeliveryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PackageDelivery.Infrastructure.Entities.EventType", "EventType")
                        .WithMany("Events")
                        .HasForeignKey("EventTypeId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("PackageDelivery.Infrastructure.Entities.Package", "Package")
                        .WithMany()
                        .HasForeignKey("PackageId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.Navigation("Delivery");

                    b.Navigation("EventType");

                    b.Navigation("Package");
                });

            modelBuilder.Entity("PackageDelivery.Infrastructure.Entities.Package", b =>
                {
                    b.HasOne("PackageDelivery.Infrastructure.Entities.Delivery", "Delivery")
                        .WithMany("Packages")
                        .HasForeignKey("DeliveryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Delivery");
                });

            modelBuilder.Entity("PackageDelivery.Infrastructure.Entities.AspNetRole", b =>
                {
                    b.Navigation("AspNetRoleClaimRoleId1Navigations");

                    b.Navigation("AspNetRoleClaimRoles");

                    b.Navigation("AspNetUserRoleRoleId1Navigations");

                    b.Navigation("AspNetUserRoleRoles");
                });

            modelBuilder.Entity("PackageDelivery.Infrastructure.Entities.AspNetUser", b =>
                {
                    b.Navigation("AspNetUserClaimUserId1Navigations");

                    b.Navigation("AspNetUserClaimUsers");

                    b.Navigation("AspNetUserLoginUserId1Navigations");

                    b.Navigation("AspNetUserLoginUsers");

                    b.Navigation("AspNetUserRoleUserId1Navigations");

                    b.Navigation("AspNetUserRoleUsers");

                    b.Navigation("AspNetUserTokenUserId1Navigations");

                    b.Navigation("AspNetUserTokenUsers");
                });

            modelBuilder.Entity("PackageDelivery.Infrastructure.Entities.Delivery", b =>
                {
                    b.Navigation("DeliveryDeliveryAttributes");

                    b.Navigation("Events");

                    b.Navigation("Packages");
                });

            modelBuilder.Entity("PackageDelivery.Infrastructure.Entities.DeliveryAttribute", b =>
                {
                    b.Navigation("DeliveryDeliveryAttributes");
                });

            modelBuilder.Entity("PackageDelivery.Infrastructure.Entities.EventType", b =>
                {
                    b.Navigation("Events");
                });
#pragma warning restore 612, 618
        }
    }
}
